site_name: Michal Public [Wiki]
site_description: Documentation for apps and scripts I have developed
site_url: https://USER.github.io/REPO/     # or custom domain
repo_url: https://github.com/USER/REPO
use_directory_urls: true

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.indexes
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.tabs.link
    - toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
  logo: assets/images/logo.svg
  favicon: assets/images/favicon.png

nav:
  - Home: index.md
  - Apps:
    - Overview: apps/_index.md
    - Sample App: apps/sample-app.md
  - Scripts:
    - Overview: scripts/_index.md
    - Sample Script: scripts/sample-script.md

plugins:
  - search
  - roamlinks

markdown_extensions:
  - admonition
  - footnotes
  - toc:
      permalink: true
  - tables
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

extra_javascript:
  - https://unpkg.com/mermaid@10.9.1/dist/mermaid.min.js
  - javascripts/init-mermaid.js

extra_css: []

extra_templates:
  - 404.html
